site_name: Notes for Compiler Principles
repo_url: https://github.com/chuan-325/comp-21sp
repo_name: chuan-325/comp-21sp
nav:
  - Home: index.md
  - Note:
      - C1 编译概论: chap_01.md
      - C2 一个简单的语法制导翻译器: chap_02.md
  - Homework:
      - hw-01-01: hw/hw_01.md
      - hw-02-01: hw/hw_02_01.md
      - hw-02-02: hw/hw_02_02.md
      - hw-03-01: hw/hw_03_01.md
      - hw-03-02: hw/hw_03_02.md
      - hw-04-01: hw/hw_04_01.md
      - hw-04-02: hw/hw_04_02.md
      - hw-04-03: hw/hw_04_03.md
theme:
  name: material
  palette:
    primary: teal
    accent: teal
  language: zh
  features:
    - search.suggest
    - search.highlight
    - navigation.top
markdown_extensions:
  - mdx_truly_sane_lists
  - attr_list
  - footnotes
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
      toc_depth: 3
plugins:
  - search:
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
